unchecked/dinstall
unchecked stuff now also in functions.
call a few functions from within dinstall, right before we run accepted.
Otherwise, with the new way of NEW, stuff from (o-)p-u-new would take
two dinstall runs before it is from there into the archive proper...

Signed-off-by: Joerg Jaspert <joerg@debian.org>

diff --git a/config/debian/common b/config/debian/common
--- a/config/debian/common
+++ b/config/debian/common
@@ -42,3 +42,48 @@ function make_buildd_dir () {
 	ln -sfT tree/${STAMP} ${incoming}/builddweb
 	find ./tree -mindepth 1 -maxdepth 1 -not -name "${STAMP}" -type d -print0 | xargs --no-run-if-empty -0 rm -rf
 }
+
+# move accepted NEW packages from stagedir into queue/accepted
+function acceptnew () {
+    cd $newstage
+    for file in $(find . -maxdepth 1 -mindepth 1 -type f -name \*.changes | sed -e "s,./,," | xargs); do
+        sed '1,/Files:/d' "${file}" | sed '/BEGIN PGP SIGNATURE/,$d' \
+            | while read notused1 notused2 notused3 notused4 NAME; do
+            if [ -z "${NAME}" ]; then
+                # Sometimes there is a newline after the Files:, ignore it
+                continue
+            fi
+            if [ -f "${NAME}" ]; then
+                mv --target-directory="${accepted}" "${NAME}"
+            else
+                log_error "Error, couldn't find file ${NAME} to move to ${accepted}"
+                exit 2
+            fi
+        done
+        mv --target-directory="${accepted}"  "${file}" "${file%%.changes}.dak"
+    done
+}
+
+# Do the unchecked processing, in case we have files.
+function do_unchecked () {
+    cd $unchecked
+
+    changes=$(find . -maxdepth 1 -mindepth 1 -type f -name \*.changes | sed -e "s,./,," | xargs)
+    report=$queuedir/REPORT
+    timestamp=$(date "+%Y-%m-%d %H:%M")
+
+    echo "$timestamp": "$changes"  >> $report
+    dak process-unchecked -a -d "$unchecked" >> $report
+    echo "--" >> $report
+}
+
+function sync_debbugs () {
+    # sync with debbugs
+    rsync -aq -e "ssh -o Batchmode=yes -o ConnectTimeout=30 -o SetupTimeout=30" --remove-source-files  $queuedir/bts_version_track/ bugs-sync:/org/bugs.debian.org/versions/queue/ftp-master/ 2>/dev/null && touch $lockdir/synced_bts_version || true
+    NOW=$(date +%s)
+    TSTAMP=$(stat -c %Y $lockdir/synced_bts_version)
+    DIFF=$(( NOW - TSTAMP ))
+    if [ $DIFF -ge 259200 ]; then
+        log "Kids, you tried your best and you failed miserably. The lesson is, never try. (Homer Simpson)"
+    fi
+}
